import { StyleSheet } from "react-native";

export default StyleSheet.create({
  NavigationButtons: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  LandingImage: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  LandingContainer: {
    backgroundColor: "white",
  },
  NeuronContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  backgroundImage: {
    position: "relative",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  CellBody: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "33%",
  },
  Dendrite: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "18%",
  },
  Axon: {
    flex: 1,
    position: "absolute",
    right: "48%",
    top: "60%",
  },
  NodeofRanvier: {
    flex: 1,
    position: "absolute",
    right: "58%",
    top: "54%",
  },
  MyelinSheath: {
    flex: 1,
    position: "absolute",
    right: "18%",
    top: "54%",
  },
  Synapse: {
    flex: 1,
    position: "absolute",
    right: "10%",
    top: "80%",
  },
  SchwannCell: {
    flex: 1,
    position: "absolute",
    right: "40%",
    top: "64%",
  },
  AxonHillock: {
    flex: 1,
    position: "absolute",
    right: "16%",
    top: "67%",
  },
  OuterBrainImage: {
    width: "100%",
    height: "50%",
    justifyContent: "center",
  },
  NeuronImage: {
    width: "100%",
    height: "60%",
    justifyContent: "center",
  },
  LandingPageImage: {
    width: 675,
    height: 475,
  },
  InnerBrainImage: {
    width: "100%",
    height: "50%",
    justifyContent: "center",
  },
  InnerBrainImageContainer: {
    position: "relative",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  ButtonContainer: {
    flex: 1,
    backgroundColor: "pink",
    alignItems: "center",
    justifyContent: "center",
  },
  BrainInteriorContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    height: "80%",
  },
  CorpusCallosum: {
    flex: 1,
    position: "absolute",
    right: "6%",
    top: "44%",
  },
  Thalamus: {
    flex: 1,
    position: "absolute",
    right: "42%",
    top: "42%",
  },
  Hypothalamus: {
    flex: 1,
    position: "absolute",
    right: "34%",
    top: "55%",
  },
  Amygdala: {
    flex: 1,
    position: "absolute",
    right: "34%",
    top: "49%",
  },
  Medulla: {
    flex: 1,
    position: "absolute",
    right: "50%",
    top: "65%",
  },
  PituitaryGland: {
    flex: 1,
    position: "absolute",
    right: "12%",
    top: "60%",
  },
  BrainStem: {
    flex: 1,
    position: "absolute",
    right: "48%",
    top: "70%",
  },
  SpinalCord: {
    flex: 1,
    position: "absolute",
    right: "58%",
    top: "75%",
  },
  BrainExteriorContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    height: "80%",
  },
  ParietalLobe: {
    flex: 1,
    position: "absolute",
    top: "35%",
    right: "14%",
  },
  FrontalLobe: {
    flex: 1,
    position: "absolute",
    top: "43%",
    right: "68%",
  },
  OccipitalLobe: {
    flex: 1,
    position: "absolute",
    right: "5%",
    top: "51%",
  },
  TemporalLobe: {
    flex: 1,
    position: "absolute",
    right: "40%",
    top: "57%",
  },
  Cerebellum: {
    flex: 1,
    position: "absolute",
    top: "65%",
    right: "18%",
  },
  Brain: {
    flex: 1,
    position: "absolute",
    right: "40%",
    top: "20%",
  },
  Heart: {
    flex: 1,
    position: "absolute",
    right: "15%",
    top: "20%",
  },
  LeftVentricle: {
    flex: 1,
    position: "absolute",
    right: "13%",
    top: "65%",
  },
  RightVentricle: {
    flex: 1,
    position: "absolute",
    right: "55%",
    top: "65%",
  },
  RightAtrium: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "45%",
  },
  LeftAtrium: {
    flex: 1,
    position: "absolute",
    right: "15%",
    top: "45%",
  },
  Aorta: {
    flex: 1,
    position: "absolute",
    right: "50%",
    top: "20%",
  },
  InfVenaCava: {
    flex: 1,
    position: "absolute",
    right: "62%",
    top: "82%",
  },
  SupVenaCava: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "30%",
  },
  PulmonaryArtery: {
    flex: 1,
    position: "absolute",
    right: "15%",
    top: "33%",
  },
  Tricuspid: {
    flex: 1,
    position: "absolute",
    right: "58%",
    top: "56%",
  },
  Mitral: {
    flex: 1,
    position: "absolute",
    right: "15%",
    top: "53%",
  },
  HeartContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    height: "80%",
  },
  HeartImage: {
    position: "relative",
    width: "100%",
    height: "70%",
  },
  HeartImageContainer: {
    position: "relative",
    justifyContent: "center",
    width: "90%",
    height: "100%",
  },
  message: {
    flex: 1,
    position: "absolute",
    alignContent: "center",
    textAlignVertical: "center",
    textAlign: "center",
    top: "10%",
  },
});
