import { StyleSheet } from "react-native";

export default StyleSheet.create({
  NavigationButtons: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  LandingImage: {
    flex: "center",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  LandingContainer: {
    backgroundColor: "white",
  },
  NeuronContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  backgroundImage: {
    flex: 20,
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },
  CellBody: {
    flex: 1,
    postion: "absolute",
    right: 135,
    top: -550,
  },
  Dendrite: {
    flex: 1,
    postion: "absolute",
    right: 135,
    top: -750,
  },
  Axon: {
    flex: 1,
    postion: "absolute",
    right: 50,
    top: -325,
  },
  NodeofRanvier: {
    flex: 1,
    postion: "absolute",
    right: -50,
    top: -450,
  },
  MyelinSheath: {
    flex: 1,
    postion: "absolute",
    right: 100,
    top: -500,
  },
  Synapse: {
    flex: 1,
    postion: "absolute",
    right: -375,
    top: -330,
  },
  SchwannCell: {
    flex: 1,
    postion: "absolute",
    right: -100,
    top: -450,
  },
  AxonHillock: {
    flex: 1,
    postion: "absolute",
    right: 25,
    top: -725,
  },
  OuterBrainImage: {
    width: 900,
    height: 725,
  },
  NeuronImage: {
    width: 775,
    height: 735,
  },
  LandingPageImage: {
    width: 675,
    height: 475,
  },
  InnerBrainImage: {
    width: 1100,
    height: 1015,
  },
  ButtonContainer: {
    flex: 1,
    backgroundColor: "pink",
    alignItems: "center",
    justifyContent: "center",
  },
  BrainInteriorContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  CorpusCallosum: {
    flex: 1,
    position: "absolute",
    right: 1180,
    top: 360,
  },
  Thalamus: {
    flex: 1,
    position: "absolute",
    right: 1085,
    top: 450,
  },
  Hypothalamus: {
    flex: 1,
    position: "absolute",
    right: 1250,
    top: 510,
  },
  Amygdala: {
    flex: 1,
    position: "absolute",
    right: 1085,
    top: 575,
  },
  Medulla: {
    flex: 1,
    position: "absolute",
    right: 1300,
    top: 780,
  },
  PituitaryGland: {
    flex: 1,
    position: "absolute",
    right: 1085,
    top: 675,
  },
  BrainStem: {
    flex: 1,
    position: "absolute",
    right: 1350,
    top: 880,
  },
  SpinalCord: {
    flex: 1,
    position: "absolute",
    right: 1375,
    top: 950,
  },
  BrainExteriorContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  ParietalLobe: {
    flex: 1,
    position: "absolute",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    top: 325,
    right: 1000,
  },
  FrontalLobe: {
    flex: 1,
    position: "absolute",
    top: 350,
    right: 1500,
  },
  OccipitalLobe: {
    flex: 1,
    position: "absolute",
    right: 900,
    top: 525,
  },
  TemporalLobe: {
    flex: 1,
    position: "absolute",
    right: 1300,
    top: 600,
  },
  Cerebellum: {
    flex: 1,
    position: "absolute",
    right: 1050,
    top: 800,
  },
  Brain: {
    flex: 1,
    position: "absolute",
    right: 1230,
    top: 100,
  },
  Heart: {
    position: "absolute",
    top: "3%",
    
  },
  LeftVentricle: {
    flex: 1,
    position: "absolute",
    right: "31%",
    top: "65%",
  },
  RightVentricle: {
    flex: 1,
    position: "absolute",
    right: "55%",
    top: "65%",
  },
  RightAtrium: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "45%",
  },
  LeftAtrium: {
    flex: 1,
    position: "absolute",
    right: "33%",
    top: "45%",
  },
  Aorta: {
    flex: 1,
    position: "absolute",
    right: "50%",
    top: "20%",
  },
  InfVenaCava: {
    flex: 1,
    position: "absolute",
    right: "62%",
    top: "82%",
  },
  SupVenaCava: {
    flex: 1,
    position: "absolute",
    right: "60%",
    top: "30%",
  },
  PulmonaryArtery: {
    flex: 1,
    position: "absolute",
    right: "38%",
    top: "28%",
  },
  Tricuspid: {
    flex: 1,
    position: "absolute",
    right: "58%",
    top: "56%",
  },
  Mitral: {
    lex: 1,
    position: "absolute",
    right: "32%",
    top: "53%",
  },
  HeartContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  HeartImage: {
    position: "relative",
    top: "-10%",
    width: 775,
    height: 735,
  },
  message: {
    flex: 1,
    position: "relative",
    
  },
});
